# Fly.io configuration for Sloposcope
app = "sloposcope"
primary_region = "lhr" # London

[build]

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/health"

[vm]
cpu_kind = "shared"
cpus = 2
memory_mb = 2048

[[vm.mounts]]
source = "sloposcope_data"
destination = "/data"
