
# Entity Grid Transition Probabilities
# Format: [from_role.to_role] = probability

[S_S]
probability = 0.60

[S_O]
probability = 0.15

[S_X]
probability = 0.10

[S_dash]
probability = 0.15

[O_S]
probability = 0.20

[O_O]
probability = 0.40

[O_X]
probability = 0.20

[O_dash]
probability = 0.20

[X_S]
probability = 0.25

[X_O]
probability = 0.25

[X_X]
probability = 0.30

[X_dash]
probability = 0.20

[dash_S]
probability = 0.30

[dash_O]
probability = 0.25

[dash_X]
probability = 0.15

[dash_dash]
probability = 0.30
